# Generated by Django 3.0.8 on 2021-04-06 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=55, verbose_name='email')),
                ('password', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=55, unique=True)),
                ('whatsappnumber', models.CharField(default='', max_length=55)),
                ('parentname', models.CharField(default='', max_length=50)),
                ('classname', models.CharField(default='', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('tag', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('ammount', models.IntegerField()),
                ('transactionid', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('coursesId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
