# Generated by Django 3.0.8 on 2021-04-09 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
